import type { AppData } from "../types";

export const INITIAL_DATA: AppData = {
  customers: [
    {
      id: "c1",
      name: "Ramesh Kumar Yadav",
      address: "Village Raipur, District Gorakhpur, UP - 273001",
      phone: "9876543210",
      notes: "Regular customer, prefers Paddy and Wheat seeds",
      transactions: [
        {
          id: "t1",
          date: "2025-03-15",
          seedType: "Paddy (HYV)",
          quantity: 5,
          unit: "Bags",
          unitRate: 2800,
          amountPaid: 12000,
          amountDue: 2000,
          dueDate: "2025-04-15",
          paymentDate: "2025-03-20",
          notes: "Kharif season purchase",
        },
        {
          id: "t2",
          date: "2025-06-10",
          seedType: "Maize Hybrid",
          quantity: 3,
          unit: "Bags",
          unitRate: 1500,
          amountPaid: 4500,
          amountDue: 0,
          dueDate: "",
          paymentDate: "2025-06-10",
        },
      ],
    },
    {
      id: "c2",
      name: "Sunita Devi Patel",
      address: "Mohalla Shanti Nagar, Lucknow, UP - 226001",
      phone: "9812345678",
      notes: "Kitchen garden enthusiast",
      transactions: [
        {
          id: "t3",
          date: "2025-02-20",
          seedType: "Tomato (Hybrid)",
          quantity: 500,
          unit: "Grams",
          unitRate: 180,
          amountPaid: 800,
          amountDue: 100,
          dueDate: "2025-03-20",
          paymentDate: "",
        },
        {
          id: "t4",
          date: "2025-05-01",
          seedType: "Okra (Bhindi)",
          quantity: 2,
          unit: "Packets",
          unitRate: 120,
          amountPaid: 240,
          amountDue: 0,
          dueDate: "",
          paymentDate: "2025-05-01",
        },
      ],
    },
    {
      id: "c3",
      name: "Mahendra Singh Chauhan",
      address: "Gram Bhaluani, Tehsil Sadar, Varanasi - 221001",
      phone: "9934567890",
      transactions: [
        {
          id: "t5",
          date: "2025-10-05",
          seedType: "Wheat (GW-496)",
          quantity: 10,
          unit: "Bags",
          unitRate: 3200,
          amountPaid: 28000,
          amountDue: 4000,
          dueDate: "2025-11-05",
          paymentDate: "2025-10-10",
        },
      ],
    },
    {
      id: "c4",
      name: "Priya Sharma",
      address: "Plot 14, Sector 7, Noida, UP - 201301",
      phone: "9845678901",
      transactions: [
        {
          id: "t6",
          date: "2025-04-12",
          seedType: "Mustard (PM-30)",
          quantity: 5,
          unit: "Kg",
          unitRate: 450,
          amountPaid: 2250,
          amountDue: 0,
          dueDate: "",
          paymentDate: "2025-04-12",
        },
        {
          id: "t7",
          date: "2025-07-20",
          seedType: "Moong (Pusa Vishal)",
          quantity: 3,
          unit: "Kg",
          unitRate: 380,
          amountPaid: 1000,
          amountDue: 140,
          dueDate: "2025-08-20",
          paymentDate: "",
        },
      ],
    },
    {
      id: "c5",
      name: "Anand Prakash Tiwari",
      address: "Near Ram Mandir, Ayodhya Road, Faizabad - 224001",
      phone: "9765432100",
      transactions: [
        {
          id: "t8",
          date: "2025-01-18",
          seedType: "Onion (Nasik Red)",
          quantity: 20,
          unit: "Packets",
          unitRate: 85,
          amountPaid: 1700,
          amountDue: 0,
          dueDate: "",
          paymentDate: "2025-01-18",
        },
      ],
    },
  ],
  suppliers: [
    {
      id: "s1",
      name: "Pioneer Seeds India Pvt. Ltd.",
      address: "Plot 42, MIDC, Pune, Maharashtra - 411019",
      phone: "9220012345",
      notes: "Maize and Sunflower hybrid supplier",
      transactions: [
        {
          id: "st1",
          date: "2025-01-10",
          seedType: "Maize Hybrid DKC-9081",
          quantity: 50,
          unit: "Bags",
          unitRate: 1200,
          amountPaid: 55000,
          amountDue: 5000,
          dueDate: "2025-02-10",
          paymentDate: "2025-01-15",
        },
        {
          id: "st2",
          date: "2025-06-05",
          seedType: "Sunflower Hybrid 6443",
          quantity: 30,
          unit: "Bags",
          unitRate: 900,
          amountPaid: 27000,
          amountDue: 0,
          dueDate: "",
          paymentDate: "2025-06-05",
        },
      ],
    },
    {
      id: "s2",
      name: "Mahyco Seeds Ltd.",
      address: "Dawalwadi, Jalna, Maharashtra - 431203",
      phone: "9234567890",
      notes: "Paddy and vegetable seeds",
      transactions: [
        {
          id: "st3",
          date: "2025-03-01",
          seedType: "Paddy MRC-7017",
          quantity: 100,
          unit: "Bags",
          unitRate: 2200,
          amountPaid: 200000,
          amountDue: 20000,
          dueDate: "2025-04-01",
          paymentDate: "2025-03-05",
        },
      ],
    },
    {
      id: "s3",
      name: "Bejo Sheetal Seeds Pvt. Ltd.",
      address: "E-9 MIDC Area, Aurangabad, Maharashtra - 431136",
      phone: "9987654321",
      transactions: [
        {
          id: "st4",
          date: "2025-02-14",
          seedType: "Tomato Hybrid TM-11",
          quantity: 5,
          unit: "Kg",
          unitRate: 4500,
          amountPaid: 20000,
          amountDue: 2500,
          dueDate: "2025-03-14",
          paymentDate: "2025-02-20",
        },
      ],
    },
    {
      id: "s4",
      name: "Kaveri Seed Company Ltd.",
      address: "513/B, Road No.92, Jubilee Hills, Hyderabad - 500033",
      phone: "9156789012",
      transactions: [
        {
          id: "st5",
          date: "2025-04-20",
          seedType: "Chilli KCH-1",
          quantity: 2,
          unit: "Kg",
          unitRate: 8000,
          amountPaid: 15000,
          amountDue: 1000,
          dueDate: "2025-05-20",
          paymentDate: "2025-04-25",
        },
        {
          id: "st6",
          date: "2025-08-15",
          seedType: "Moong Green Gold",
          quantity: 20,
          unit: "Bags",
          unitRate: 320,
          amountPaid: 6400,
          amountDue: 0,
          dueDate: "",
          paymentDate: "2025-08-15",
        },
      ],
    },
    {
      id: "s5",
      name: "Rasi Seeds Pvt. Ltd.",
      address: "123, Anna Salai, Attur, Salem, TN - 636102",
      phone: "9045678901",
      transactions: [
        {
          id: "st7",
          date: "2025-09-10",
          seedType: "Wheat DBW-222",
          quantity: 200,
          unit: "Bags",
          unitRate: 2800,
          amountPaid: 500000,
          amountDue: 60000,
          dueDate: "2025-10-10",
          paymentDate: "2025-09-15",
        },
      ],
    },
  ],
  stock: [
    {
      id: "sk1",
      name: "Maize Hybrid DKC-9081",
      category: "Cereal",
      bags: 45,
      packets: 0,
      kg: 0,
      grams: 0,
      costPrice: 1200,
      sellPrice: 1500,
      reorderLevel: 10,
      description: "High-yielding maize hybrid, suitable for Kharif season",
      imageUrl: "/assets/generated/seeds-icon-transparent.dim_200x200.png",
    },
    {
      id: "sk2",
      name: "Paddy MRC-7017",
      category: "Cereal",
      bags: 80,
      packets: 0,
      kg: 0,
      grams: 0,
      costPrice: 2200,
      sellPrice: 2800,
      reorderLevel: 20,
      description: "Medium duration paddy with excellent grain quality",
      imageUrl: "/assets/generated/seeds-icon-transparent.dim_200x200.png",
    },
    {
      id: "sk3",
      name: "Wheat GW-496",
      category: "Cereal",
      bags: 120,
      packets: 0,
      kg: 0,
      grams: 0,
      costPrice: 2800,
      sellPrice: 3200,
      reorderLevel: 30,
      description: "High protein wheat variety for Rabi season",
      imageUrl: "/assets/generated/seeds-icon-transparent.dim_200x200.png",
    },
    {
      id: "sk4",
      name: "Tomato Hybrid TM-11",
      category: "Vegetable",
      bags: 0,
      packets: 150,
      kg: 2,
      grams: 500,
      costPrice: 350,
      sellPrice: 480,
      reorderLevel: 20,
      description: "Determinate hybrid tomato, disease resistant",
      imageUrl: "/assets/generated/seeds-icon-transparent.dim_200x200.png",
    },
    {
      id: "sk5",
      name: "Onion Nasik Red",
      category: "Vegetable",
      bags: 0,
      packets: 200,
      kg: 5,
      grams: 0,
      costPrice: 60,
      sellPrice: 85,
      reorderLevel: 30,
      description: "Popular red onion variety with long shelf life",
      imageUrl: "/assets/generated/seeds-icon-transparent.dim_200x200.png",
    },
    {
      id: "sk6",
      name: "Mustard PM-30",
      category: "Oilseed",
      bags: 0,
      packets: 0,
      kg: 85,
      grams: 0,
      costPrice: 380,
      sellPrice: 450,
      reorderLevel: 15,
      description: "High oil content mustard for Rabi season",
      imageUrl: "/assets/generated/seeds-icon-transparent.dim_200x200.png",
    },
    {
      id: "sk7",
      name: "Chilli KCH-1",
      category: "Vegetable",
      bags: 0,
      packets: 80,
      kg: 1,
      grams: 200,
      costPrice: 600,
      sellPrice: 800,
      reorderLevel: 10,
      description: "Pungent chilli hybrid, suitable for processing",
      imageUrl: "/assets/generated/seeds-icon-transparent.dim_200x200.png",
    },
    {
      id: "sk8",
      name: "Moong Pusa Vishal",
      category: "Pulse",
      bags: 0,
      packets: 0,
      kg: 65,
      grams: 0,
      costPrice: 300,
      sellPrice: 380,
      reorderLevel: 10,
      description: "Early maturing moong with bold green seeds",
      imageUrl: "/assets/generated/seeds-icon-transparent.dim_200x200.png",
    },
  ],
  bills: [
    {
      id: "b1",
      billNumber: "LBB-0001",
      customerId: "c1",
      customerName: "Ramesh Kumar Yadav",
      customerPhone: "9876543210",
      customerAddress: "Village Raipur, District Gorakhpur, UP - 273001",
      purchaseDate: "2025-03-15",
      dueDate: "2025-04-15",
      paymentDate: "2025-03-20",
      lineItems: [
        {
          id: "li1",
          productName: "Paddy MRC-7017",
          quantity: 5,
          unit: "Bags",
          unitRate: 2800,
          amount: 14000,
        },
      ],
      discount: 0,
      tax: 0,
      totalAmount: 14000,
      finalAmount: 14000,
      status: "Partial",
    },
    {
      id: "b2",
      billNumber: "LBB-0002",
      customerId: "c3",
      customerName: "Mahendra Singh Chauhan",
      customerPhone: "9934567890",
      customerAddress: "Gram Bhaluani, Tehsil Sadar, Varanasi - 221001",
      purchaseDate: "2025-10-05",
      dueDate: "2025-11-05",
      paymentDate: "2025-10-10",
      lineItems: [
        {
          id: "li2",
          productName: "Wheat GW-496",
          quantity: 10,
          unit: "Bags",
          unitRate: 3200,
          amount: 32000,
        },
      ],
      discount: 500,
      tax: 0,
      totalAmount: 32000,
      finalAmount: 31500,
      status: "Partial",
    },
    {
      id: "b3",
      billNumber: "LBB-0003",
      customerId: "c4",
      customerName: "Priya Sharma",
      customerPhone: "9845678901",
      customerAddress: "Plot 14, Sector 7, Noida, UP - 201301",
      purchaseDate: "2025-04-12",
      dueDate: "",
      paymentDate: "2025-04-12",
      lineItems: [
        {
          id: "li3",
          productName: "Mustard PM-30",
          quantity: 5,
          unit: "Kg",
          unitRate: 450,
          amount: 2250,
        },
      ],
      discount: 0,
      tax: 0,
      totalAmount: 2250,
      finalAmount: 2250,
      status: "Paid",
    },
  ],
  seedCatalog: [
    {
      id: "sc1",
      name: "Maize",
      category: "Cereal",
      description:
        "Versatile Kharif crop, used for food, feed and industrial purposes. Thrives in warm climate.",
      season: "Kharif",
      region: "All India",
    },
    {
      id: "sc2",
      name: "Paddy",
      category: "Cereal",
      description:
        "Staple food crop of India, grown in waterlogged conditions. Major Kharif crop.",
      season: "Kharif",
      region: "North & South India",
    },
    {
      id: "sc3",
      name: "Wheat",
      category: "Cereal",
      description:
        "Primary Rabi cereal crop, grown in cool dry weather. Major food grain of North India.",
      season: "Rabi",
      region: "North India",
    },
    {
      id: "sc4",
      name: "Rice",
      category: "Cereal",
      description:
        "Short-grain aromatic rice varieties. Requires high rainfall or irrigation.",
      season: "Kharif",
      region: "Pan India",
    },
    {
      id: "sc5",
      name: "Mustard",
      category: "Oilseed",
      description:
        "Important Rabi oilseed crop. High oil content seeds used for edible oil production.",
      season: "Rabi",
      region: "Rajasthan, MP, UP",
    },
    {
      id: "sc6",
      name: "Sunflower",
      category: "Oilseed",
      description:
        "High-yielding oilseed with good adaptability. Grown in both Kharif and Rabi seasons.",
      season: "Kharif/Rabi",
      region: "Karnataka, AP, Maharashtra",
    },
    {
      id: "sc7",
      name: "Soybean",
      category: "Oilseed",
      description:
        "Major Kharif oilseed and protein crop. Rich in protein and edible oil.",
      season: "Kharif",
      region: "MP, Maharashtra, Rajasthan",
    },
    {
      id: "sc8",
      name: "Tomato",
      category: "Vegetable",
      description:
        "Most popular vegetable crop with multiple hybrid varieties. Grown throughout the year.",
      season: "Year Round",
      region: "Pan India",
    },
    {
      id: "sc9",
      name: "Onion",
      category: "Vegetable",
      description:
        "Essential culinary vegetable. Long shelf life varieties suitable for storage and export.",
      season: "Rabi",
      region: "Maharashtra, Karnataka, MP",
    },
    {
      id: "sc10",
      name: "Potato",
      category: "Vegetable",
      description:
        "Important Rabi vegetable crop. Wide adaptability and high market demand.",
      season: "Rabi",
      region: "UP, West Bengal, Punjab",
    },
    {
      id: "sc11",
      name: "Chilli",
      category: "Vegetable",
      description:
        "High value spice and vegetable crop. Both fresh market and processing types available.",
      season: "Kharif",
      region: "AP, Telangana, Karnataka",
    },
    {
      id: "sc12",
      name: "Brinjal",
      category: "Vegetable",
      description:
        "Long season vegetable crop with purple, green and white varieties.",
      season: "Year Round",
      region: "Pan India",
    },
    {
      id: "sc13",
      name: "Cauliflower",
      category: "Vegetable",
      description:
        "Cool season Rabi vegetable. Early and late maturing varieties available.",
      season: "Rabi",
      region: "North India",
    },
    {
      id: "sc14",
      name: "Cabbage",
      category: "Vegetable",
      description:
        "Cool weather vegetable with round compact heads. Good storage life.",
      season: "Rabi",
      region: "North & NE India",
    },
    {
      id: "sc15",
      name: "Okra (Bhindi)",
      category: "Vegetable",
      description:
        "Fast growing summer vegetable. High yielding hybrid varieties available.",
      season: "Kharif",
      region: "Pan India",
    },
    {
      id: "sc16",
      name: "Pumpkin",
      category: "Vegetable",
      description:
        "Warm season cucurbit with high nutritional value. Dual-purpose vegetable and fodder.",
      season: "Kharif",
      region: "Pan India",
    },
    {
      id: "sc17",
      name: "Cucumber",
      category: "Vegetable",
      description:
        "Popular summer salad vegetable. Parthenocarpic hybrids for protected cultivation.",
      season: "Kharif",
      region: "Pan India",
    },
    {
      id: "sc18",
      name: "Moong",
      category: "Pulse",
      description:
        "Short duration summer pulse rich in protein. Can be grown after wheat harvest.",
      season: "Zaid/Kharif",
      region: "Rajasthan, UP, MP",
    },
    {
      id: "sc19",
      name: "Urad",
      category: "Pulse",
      description:
        "Black gram pulse with high protein content. Important dal crop of India.",
      season: "Kharif",
      region: "South & Central India",
    },
    {
      id: "sc20",
      name: "Chana",
      category: "Pulse",
      description:
        "Largest pulse crop of India. Both desi and kabuli types available.",
      season: "Rabi",
      region: "MP, Rajasthan, Maharashtra",
    },
  ],
};

export const MONTHLY_SALES_2025 = [
  { month: "Jan", sales: 48000, profit: 14400, expenses: 33600 },
  { month: "Feb", sales: 62000, profit: 19220, expenses: 42780 },
  { month: "Mar", sales: 125000, profit: 38750, expenses: 86250 },
  { month: "Apr", sales: 89000, profit: 27590, expenses: 61410 },
  { month: "May", sales: 71000, profit: 21300, expenses: 49700 },
  { month: "Jun", sales: 95000, profit: 28500, expenses: 66500 },
  { month: "Jul", sales: 82000, profit: 24600, expenses: 57400 },
  { month: "Aug", sales: 68000, profit: 20400, expenses: 47600 },
  { month: "Sep", sales: 115000, profit: 34500, expenses: 80500 },
  { month: "Oct", sales: 145000, profit: 43500, expenses: 101500 },
  { month: "Nov", sales: 112000, profit: 33600, expenses: 78400 },
  { month: "Dec", sales: 78000, profit: 23400, expenses: 54600 },
];

export const ANNUAL_SALES = [
  { year: "2023", sales: 820000, profit: 246000 },
  { year: "2024", sales: 1050000, profit: 315000 },
  { year: "2025", sales: 1090000, profit: 327000 },
];
